name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -C /home/runner/work/noc/noc V=1
    - name: make test
      run: make -C /home/runner/work/noc/noc V=1 test
